name: Release
on: [workflow_dispatch]
jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        yarn install --immutable

    - name: Package
      run: yarn package

    - name: Publish Release on Github
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "${GITHUB_REF_NAME}"
        prerelease: false
        files: |
          release/build/*.zip
